### ISSUE TITLE
Universal code copying

### ISSUE THREAD

**Issue by createcandle** [TheStaticTurtle/Open433#3]
I saw your project on Hackaday, nice job!

Last year I developed Arduino code that can clone and/or detect any 433mhz signal. By using compression it can even store up to 20 of these signals in eeprom.

By not relying on RCSwitch it can basically support any 433mhz power socket, and can detect and recognise the signals from any 433mhz window sensors, doorbells, and so forth. Might be interesting for your use case?

More here:
https://www.candlesmarthome.com/signal-hub

And the code can be found here:
https://github.com/createcandle/Devices/blob/master/Signal-hub/Signal-hub.ino

**Comment by TheStaticTurtle** [comment]
Would be interesting but in order to not lose the home assistant component it would demand a big re-implementation to transfer the code each time instead of storing in the device. 
Moreover, rc-switch already supports a great variety of outlets/lights even doorbells IIRC.
Your project looks really great but I don't have the time right now to re-implement +2000 lines of code into it right now (especially figuring out which part I need to keep and which I can throw away)
Not saying a "raw" mode won't happen in the future but not right now.

Thanks anyway.
